esphome:
  name: environment-weatherstation
  platform: ESP32
  board: esp-wrover-kit

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Environment Weatherstation"
    password: "Ftr3lLgbeWxu"

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: !secret encryption_key

ota:
  password: !secret ota_password

esp32_ble_tracker:

i2c:
  sda: GPIO21
  scl: GPIO22
  scan: true
  frequency: 100kHz

dallas:
  - pin: GPIO4
    update_interval: 20s

sensor:

  - platform: dallas
    address: 0x38000001C87FD228
    name: "Weather Station Temperature of Light Sensor"


  - platform: bme280
    temperature:
      name: "Weather Station Temperature (BME280)"
    pressure:
      name: "Weather Station Pressure"
    humidity:
      name: "Weather Station Humidity (BME280)"
    address: 0x76
    update_interval: 30s
    
  - platform: sht3xd
    temperature:
      name: "Weather Station Temperature (SHT3x)"
    humidity:
      name: "Weather Station Humidity (SHT3x)"
    address: 0x44
    update_interval: 10s
  
  - platform: tcs34725
    red_channel:
      name: "Weather Station Red Channel"
    green_channel:
      name: "Weather Station Green Channel"
    blue_channel:
      name: "Weather Station Blue Channel"
    clear_channel:
      name: "Weather Station Clear Channel"
    illuminance:
      name: "Weather Station Illuminance (TCS34725)"
    color_temperature:
      name: "Weather Station Color Temperature"
    gain: 1x
    integration_time: 50ms
    address: 0x29
    update_interval: 10s
    
  - platform: wifi_signal
    name: "Weather Station RSSI"
    update_interval: 10s

  - platform: max44009
    name: "Weather Station Illuminance (MAX44009)"
    address: 0x4A
    update_interval: 10s
    
    
    
  - platform: tsl2561
    name: "Weather Station Illuminance (TSL2561)"
    address: 0x39
    update_interval: 10s
    
    
    
    
    
  - platform: bh1750
    name: "Weather Station Illuminance (BH1750)"
    address: 0x23
    update_interval: 10s


