esphome:
  name: fireplace
  platform: ESP8266
  board: nodemcuv2

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Fireplace Fallback Hotspot"
    password: "5pjZPZ48PgaQ"

captive_portal:

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: !secret encryption_key

ota:
  password: !secret ota_password
  
  
# Example configuration entry
spi:
  miso_pin: GPIO12
  clk_pin: GPIO14

sensor:
  - platform: max6675
    name: "Fireplace Exhaust"
    cs_pin: GPIO15
    update_interval: 10s
