esphome:
  name: growbox2
  platform: ESP8266
  board: d1_mini



# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: !secret encryption_key

web_server:
  port: 80
ota:
  password: !secret ota_password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password


  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Growbox2 Fallback Hotspot"
    password: "LvRqVrx33aO9"

i2c:
  scan: true

dallas:
  - pin: GPIO2
  

sensor:
  - platform: scd4x
    update_interval: 60s
    co2:
      id: scd41_co2
      name: "Growbox CO2"
    temperature:
      id: scd41_temperature
      name: "Growbox Temperature SCD41"
    humidity:
      id: scd41_humidity
      name: "Growbox Humidity SCD41"


  - platform: sht3xd
    temperature:
      name: "Growbox Temperature SHT30"
    humidity:
      name: "Growbox Humidity SHT30"
    address: 0x44
    update_interval: 60s
    
    
  - platform: dallas
    address: 0xF3000001C8AD7F28
    name: "Growbox Water Tank Temperature"
    
  
  - platform: qmp6988
    temperature:
      name: "Growbox Temperature QMP6988"
      oversampling: 16x
    pressure:
      name: "Growbox Pressure QMP6988"
      oversampling: 16x
    address: 0x70
    update_interval: 20s
    iir_filter: 2x
