esphome:
  name: pvctrl1

esp32:
  board: esp32dev
#  framework:
#    type: esp-idf



wifi:
  ssid: !secret wifi2_ssid
  password: !secret wifi2_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "PV Control 1"
    password: "hFG17m6QWM9r"

time:
  - platform: sntp
    id: sntp_time
    servers: "adc.ad.kolins.cz"

web_server:
  port: 80
  local: true

# Enable logging
logger:
  baud_rate: 115200
  hardware_uart: UART0
#mqtt:
#  broker: net.ad.kolins.cz
#  discovery: true      

# Enable Home Assistant API
api:
  encryption:
    key: !secret encryption_key

ota:
  password: !secret ota_password

uart:
  - id: modbus_uart
    tx_pin: GPIO27
    rx_pin: GPIO12
    baud_rate: 115200
    

  - id: ABB
    tx_pin: GPIO25
    rx_pin: GPIO26
    baud_rate: 115200
    

modbus:
  uart_id: modbus_uart
  flow_control_pin: GPIO14
  id: modbus1

modbus_controller:
  - id: epever
    ## the Modbus device addr
    address: 0x1
    modbus_id: modbus1
    #setup_priority: -10
    command_throttle: 100ms
    update_interval: 20s

dallas:
  - pin: GPIO32
    update_interval: 20s

# binary_sensor:

  
sensor:
  - platform: dallas
    address: 0x3db183a911646128
    name: "PV Control cabinet Temperature"
 
# # -----------------------EPEVER------------------- 
  - platform: modbus_controller
    modbus_controller_id: epever
    id: epever1_input_power
    name: "Epever array input power"
    address: 0x3102
    unit_of_measurement: "W" ## for any other unit the value is returned in minutes
    register_type: read
    value_type: U_DWORD_R
    accuracy_decimals: 1
    filters:
      - multiply: 0.01

# -----------------------Outputs-------------------

switch:

  - platform: gpio
    id: pvctrl1_relay1
    name: "PV Control Relay 1"  
    pin: GPIO4
    inverted: true

  - platform: gpio
    id: pvctrl1_relay2
    name: "PV Control Relay 2"  
    pin: GPIO16
    inverted: true

  - platform: gpio
    id: pvctrl1_relay3
    name: "PV Control Relay 3"  
    pin: GPIO17
    inverted: true

  - platform: gpio
    id: pvctrl1_relay4
    name: "PV Control Relay 4"  
    pin: GPIO5
    inverted: true

  - platform: gpio
    id: pvctrl1_relay5
    name: "PV Control Relay 5"  
    pin: GPIO18
    inverted: true

  - platform: gpio
    id: pvctrl1_relay6
    name: "PV Control Relay 6"  
    pin: GPIO19
    inverted: true



